---
- name: Implement exam
  hosts: all

  tasks:

  - name: Set authorized keys from controller machine
    authorized_key:
      user: exam
      state: present
      key: "{{ lookup('file', '/home/exam/.ssh/id_rsa.pub') }}"


  - name: Set includedir in sudoers
    lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
#      validate: "/usr/sbin/visudo -cf %s"